extend = "$RUFF_SHARED_CFGFILE"
cache-dir = ".dev/tmp/ruff"

[lint]
ignore = [
	"implicit-namespace-package",  # INP001
    # --- temporary ---
    "missing-copyright-notice",    # CPY001
]

[lint.per-file-ignores]
"**/.dev/emendations/*/*.py" = [
	"invalid-module-name",        # N999
	"implicit-namespace-package", # INP001
]
