[project]
name = "htmlspeccer"
version = "0.7.7"
description = "Convertor of the WHATWG HTML Living Standard specification to machine-readable data"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "faust-cchardet>=2.1.20",
    "lxml>=4.9.0",
    "python-slugify>=8.0.4",
    "pyyaml>=6.0",
]

[tool.ruff]
extend = "$PYPROJECT_DEFAULT_CFG"
cache-dir = ".dev/tmp/ruff"

[tool.ruff.lint]
ignore = [
	"implicit-namespace-package",  # INP001
    # --- temporary ---
    "missing-copyright-notice",    # CPY001
]

[tool.ruff.lint.per-file-ignores]
"**/.dev/emendations/*/*.py" = [
	"invalid-module-name",        # N999
	"implicit-namespace-package", # INP001
]

[tool.distutils.egg_info]
egg_base = ".dev/tmp"