name: update README

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["publish data"]
    types: [completed]

permissions:
  contents: write

jobs:
  update_last_updated:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 26

      - name: Acquire specs
        run: make acquire

      - name: Update README
        run: ./.dev/bin/update-readme-source-last-updated.js

      - name: Commit changes
        run: |
          if git diff --quiet README.md; then
            echo "README already up-to-date."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md
          git commit -m "docs(README): update source timestamps"
          git push
